version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - db-volume:/data/db

volumes:
  db-volume:
